### ISSUE TITLE
java.lang.IllegalArgumentException: The given array must be 16 bytes long

### ISSUE THREAD

**Issue by Zuckonit** [maltalex/ineter#10]
look at this IP：
336294682933583715844663186250927177728

**Comment by maltalex** [comment]
Could you clarify?
Is that a decimal representation? Where are you seeing this exception?

**Comment by maltalex** [comment]
Okay, so it looks like that's the decimal representation of `fd00::`. How are you converting it to an array?

**Comment by Zuckonit** [comment]
byte[] s = new BigInteger("336294682933583715844663186250927177728").toByteArray();
IPv6Address.of(s).toString();

**Comment by maltalex** [comment]
Yeah, that code returns an array with 17 bytes. IPv6 addresses have 16 bytes, hence the exception. 

The problem is that `BigInteger` treats the IP Address as a numeric value, so it tries to preserve its sign. The binary representation of `336294682933583715844663186250927177728` is `11111101 00000000 00000000 00000000....`. Note that it starts with a binary `1` when written as 128 bits. So to prevent the value from appearing negative, `BigInteger` prepends a 17th byte: `00000000 11111101 00000000 00000000 00000000....` . A "smaller" address would return 16 bytes as expected (note the first digit):

```
jshell> byte[] byteArray = new BigInteger("136294682933583715844663186250927177728").toByteArray();
byteArray ==> byte[16] { 102, -119, 102, -81, 74, -14, 119, 11, ... 1, -69, -128, 0, 0, 0, 0 }
```

The length is 16 for the smaller address.

Anyway, the problem is you're treating IP addresses as numeric values without taking the sign into account. Internally, ineter does this type of thing a lot, but it's often tricky exactly because of problems like this. If you treat IP address numerically, you need to make sure you use _unsigned_ arithmetic.

Can you tell me a bit about your use case? Why are you using decimal IPv6 addresses? The hex representation is painful enough, decimal is just awful. I've never seen anyone do that.

**Comment by Zuckonit** [comment]
another library fix this
